name: Deploy static site to Netlify

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Netlify (Production)
        uses: netlify/actions/cli@v4
        with:
          args: deploy --dir=. --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.nfp_svkuBHZTY7irgqthUMCJbfGfsAWziM5N15b1 }}
          NETLIFY_SITE_ID: ${{ secrets.57c098af-d04e-4cb2-8a06-617be974edf5 }}
